name: complete run

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-full:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository - around 25s
        uses: actions/checkout@v4

      - name: Set up uv (cold start, no caching) - around 2s
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.13"
          activate-environment: "true"
          enable-cache: "false"
          restore-cache: "false"
          save-cache: "false"
          cache-python: "false"
          
      - name: Sync dependencies - around 35s
        run: uv sync
        
      - name: Run training
        run: |
          export HYDRA_FULL_ERROR=1
          uv run python src/train.py training.max_epochs=1
          
